name: 'Sarthak AI Code Reviewer'
description: 'Reviews Pull Requests using OpenAI API'
author: 'Antigravity'
inputs:
  openai_api_key:
    description: 'OpenAI API Key'
    required: false
  github_token:
    description: 'GitHub Token'
    required: true
    default: ${{ github.token }}
  model:
    description: 'OpenAI Model to use'
    required: false
    default: 'gpt-4-turbo'
  fail_on_findings:
    description: 'Fail the workflow if AI finds issues at or above the severity threshold'
    required: false
    default: 'false'
  fail_on_severity:
    description: 'Severity threshold used when fail_on_findings is true (low|medium|high|critical)'
    required: false
    default: 'high'
runs:
  using: 'node20'
  main: 'dist/index.js'
