name: 'Sarthak AI Code Reviewer'
description: 'Reviews Pull Requests using OpenAI API'
author: 'Antigravity'
inputs:
  openai_api_key:
    description: 'OpenAI API Key'
    required: false
  github_token:
    description: 'GitHub Token'
    required: true
    default: ${{ github.token }}
  model:
    description: 'OpenAI Model to use'
    required: false
    default: 'gpt-4-turbo'
runs:
  using: 'node20'
  main: 'dist/index.js'
