name: 'Sarthak AI Code Reviewer'
description: 'Enterprise v1 platform-backed review trigger action'
author: 'Antigravity'
inputs:
  platform_base_url:
    description: 'Platform API base URL (for example https://api.your-company.com)'
    required: true
  platform_token:
    description: 'Platform action token for POST /v1/actions/reviews/trigger'
    required: true
  workflow_run_id:
    description: 'Optional workflow run identifier forwarded to platform API'
    required: false
  request_timeout_ms:
    description: 'Request timeout in milliseconds for platform API trigger call'
    required: false
    default: '15000'
runs:
  using: 'node20'
  main: 'dist/index.js'
